/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMerkleAnchorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchRegisterMerkleRoots"
      | "getRootOwner"
      | "getRootsByUser"
      | "getTotalActiveRoots"
      | "getUserRootCount"
      | "isRootRegistered"
      | "registerMerkleRoot"
      | "removeRoot"
      | "verifyProof"
      | "verifyProofWithRoot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyAction"
      | "MerkleRootRegistered"
      | "MerkleRootRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchRegisterMerkleRoots",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRootOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRootsByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalActiveRoots",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRootCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRootRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMerkleRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [AddressLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProofWithRoot",
    values: [BytesLike, BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchRegisterMerkleRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRootOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRootsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalActiveRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRootCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRootRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProofWithRoot",
    data: BytesLike
  ): Result;
}

export namespace EmergencyActionEvent {
  export type InputTuple = [admin: AddressLike, action: string];
  export type OutputTuple = [admin: string, action: string];
  export interface OutputObject {
    admin: string;
    action: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerkleRootRegisteredEvent {
  export type InputTuple = [user: AddressLike, root: BytesLike];
  export type OutputTuple = [user: string, root: string];
  export interface OutputObject {
    user: string;
    root: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerkleRootRemovedEvent {
  export type InputTuple = [user: AddressLike, root: BytesLike];
  export type OutputTuple = [user: string, root: string];
  export interface OutputObject {
    user: string;
    root: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMerkleAnchorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IMerkleAnchorRegistry;
  waitForDeployment(): Promise<this>;

  interface: IMerkleAnchorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchRegisterMerkleRoots: TypedContractMethod<
    [roots: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getRootOwner: TypedContractMethod<[root: BytesLike], [string], "view">;

  getRootsByUser: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getTotalActiveRoots: TypedContractMethod<[], [bigint], "view">;

  getUserRootCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  isRootRegistered: TypedContractMethod<[root: BytesLike], [boolean], "view">;

  registerMerkleRoot: TypedContractMethod<
    [root: BytesLike],
    [void],
    "nonpayable"
  >;

  removeRoot: TypedContractMethod<[root: BytesLike], [void], "nonpayable">;

  verifyProof: TypedContractMethod<
    [user: AddressLike, proof: BytesLike[], leaf: BytesLike],
    [boolean],
    "view"
  >;

  verifyProofWithRoot: TypedContractMethod<
    [root: BytesLike, proof: BytesLike[], leaf: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchRegisterMerkleRoots"
  ): TypedContractMethod<[roots: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRootOwner"
  ): TypedContractMethod<[root: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRootsByUser"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalActiveRoots"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserRootCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRootRegistered"
  ): TypedContractMethod<[root: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerMerkleRoot"
  ): TypedContractMethod<[root: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeRoot"
  ): TypedContractMethod<[root: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [user: AddressLike, proof: BytesLike[], leaf: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyProofWithRoot"
  ): TypedContractMethod<
    [root: BytesLike, proof: BytesLike[], leaf: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "EmergencyAction"
  ): TypedContractEvent<
    EmergencyActionEvent.InputTuple,
    EmergencyActionEvent.OutputTuple,
    EmergencyActionEvent.OutputObject
  >;
  getEvent(
    key: "MerkleRootRegistered"
  ): TypedContractEvent<
    MerkleRootRegisteredEvent.InputTuple,
    MerkleRootRegisteredEvent.OutputTuple,
    MerkleRootRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MerkleRootRemoved"
  ): TypedContractEvent<
    MerkleRootRemovedEvent.InputTuple,
    MerkleRootRemovedEvent.OutputTuple,
    MerkleRootRemovedEvent.OutputObject
  >;

  filters: {
    "EmergencyAction(address,string)": TypedContractEvent<
      EmergencyActionEvent.InputTuple,
      EmergencyActionEvent.OutputTuple,
      EmergencyActionEvent.OutputObject
    >;
    EmergencyAction: TypedContractEvent<
      EmergencyActionEvent.InputTuple,
      EmergencyActionEvent.OutputTuple,
      EmergencyActionEvent.OutputObject
    >;

    "MerkleRootRegistered(address,bytes32)": TypedContractEvent<
      MerkleRootRegisteredEvent.InputTuple,
      MerkleRootRegisteredEvent.OutputTuple,
      MerkleRootRegisteredEvent.OutputObject
    >;
    MerkleRootRegistered: TypedContractEvent<
      MerkleRootRegisteredEvent.InputTuple,
      MerkleRootRegisteredEvent.OutputTuple,
      MerkleRootRegisteredEvent.OutputObject
    >;

    "MerkleRootRemoved(address,bytes32)": TypedContractEvent<
      MerkleRootRemovedEvent.InputTuple,
      MerkleRootRemovedEvent.OutputTuple,
      MerkleRootRemovedEvent.OutputObject
    >;
    MerkleRootRemoved: TypedContractEvent<
      MerkleRootRemovedEvent.InputTuple,
      MerkleRootRemovedEvent.OutputTuple,
      MerkleRootRemovedEvent.OutputObject
    >;
  };
}
