/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIdentityAnchor } from "./IIdentityAnchor";
export type { IMerkleAnchorRegistry } from "./IMerkleAnchorRegistry";
