/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBadgeNFT } from "./IBadgeNFT";
export type { IIdentityAnchor } from "./IIdentityAnchor";
export type { IMerkleAnchorRegistry } from "./IMerkleAnchorRegistry";
export type { IModeratorRegistry } from "./IModeratorRegistry";
