/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BadgeNFT } from "./BadgeNFT";
export type { IdentityAnchor } from "./IdentityAnchor";
export type { MerkleAnchorRegistry } from "./MerkleAnchorRegistry";
