/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as openzeppelin from "./@openzeppelin";
export { IdentityAnchor__factory } from "./IdentityAnchor__factory";
