/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BadgeNFT__factory } from "./BadgeNFT__factory";
export { IdentityAnchor__factory } from "./IdentityAnchor__factory";
export { MerkleAnchorRegistry__factory } from "./MerkleAnchorRegistry__factory";
