/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IIdentityAnchor__factory } from "./IIdentityAnchor__factory";
export { IMerkleAnchorRegistry__factory } from "./IMerkleAnchorRegistry__factory";
